---
- name: Install Rancher CLI
  shell: "curl -kL {{rancher_cli_download_url}} | tar zx --strip-components 2 -C /usr/local/bin"
  args:
    creates: /usr/local/bin/rancher
  become: yes
  when: rancher_cli_install

- name: Set permissions on rancher
  file: path=/usr/local/bin/rancher mode=0755
  become: yes
  when: rancher_cli_install

- name: Install Rancher Compose
  shell: "curl -kL {{rancher_compose_download_url}} | tar zx --strip-components 2 -C /usr/local/bin"
  args:
    creates: /usr/local/bin/rancher-compose
  become: yes
  when: rancher_compose_install

- name: Set permissions on rancher-compose
  file: path=/usr/local/bin/rancher-compose mode=0755
  become: yes
  when: rancher_compose_install

- name: Create the Rancher config directory
  file:
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    path: "~{{ ansible_user }}/.rancher"
    state: directory
    mode: 0755

- name: Create the Rancher config
  template:
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    src: cli.json.j2
    dest: "~{{ ansible_user }}/.rancher/cli.json"
    mode: 0600
